### ISSUE TITLE
Core algorithm bugs

### ISSUE THREAD

**Issue by friedger** [KB1RD/matrix-notepad#20]
Original text:

```
Collaborative Text Editing

This document described

Hello
```

Result for the other user:
```
Collaborative TtinThis docuentm describedHello
```

**Comment by KB1RD** [comment]
Thank you for pointing this out. I'm actually aware of issues like these, but I haven't opened an issue yet. The issues are due to bugs in the core algorithm and I've opened an issue [here](https://github.com/KB1RD/logootish-js/issues/6) to keep track of these. In short, I'm not fixing these issues in the *current* algorithm version because introducing conflict resolution creates major changes. I'm very close to finishing this new version (but I've said that for like a month) and then I'll work on introducing it into the Notepad and writing unit tests. I haven't been able to maintain any of my projects much over the last few months because I've had a ton of schoolwork.

The issues that you encountered are not due to empty lines or cursor moving specifically, though. The algorithm just receives where text insertions/removals are and translates these into Logoot positions to be sent over Matrix. The algorithm keeps track of which positions in the text editor map onto which Logoot positions. The problem is that sometimes its record of where all the text is gets out of sync with what's actually on the screen. That's what's happening here :)

**Comment by KB1RD** [comment]
AFAIK, `v0.2.2` fixes them all. The trick that I've found works well is to run pseudorandom "practical" tests on the algorithm while in development. That way, even if I miss something that code coverage doesn't catch before release, the practical tests will break the algorithm by brute force. Feel free to re-open if other algorithm issues are found.
